/********************************************************************************
** Form generated from reading UI file 'charsheet.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CHARSHEET_H
#define UI_CHARSHEET_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QTextEdit>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CharSheet
{
public:
    QAction *actionNew_Character;
    QAction *actionLoad_Character;
    QAction *actionSave_Character;
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *pic;
    QTextEdit *textEdit;
    QLabel *label_7;
    QLabel *label_2;
    QLabel *label_5;
    QLabel *label_4;
    QLineEdit *Wieght;
    QLabel *label_12;
    QLabel *label_8;
    QLabel *label_11;
    QComboBox *comboBox;
    QLineEdit *lineEdit;
    QLineEdit *Religion;
    QLineEdit *Size;
    QLineEdit *CharName;
    QLabel *label;
    QLabel *label_10;
    QLabel *label_6;
    QPushButton *pushButton;
    QLabel *label_3;
    QLabel *label_9;
    QLineEdit *Height;
    QListWidget *listWidget;
    QLineEdit *lineEdit_7;
    QLineEdit *lineEdit_8;
    QWidget *tab_2;
    QTableWidget *tableWidget;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEdit_2;
    QLabel *label_15;
    QLineEdit *lineEdit_3;
    QLabel *label_16;
    QLineEdit *lineEdit_4;
    QLabel *label_17;
    QLineEdit *lineEdit_5;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *lineEdit_6;
    QTableWidget *tableWidget_3;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QLabel *label_20;
    QTableWidget *tableWidget_2;
    QWidget *tab_4;
    QLabel *label_21;
    QProgressBar *progressBar;
    QLabel *label_22;
    QProgressBar *progressBar_2;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QTableWidget *tableWidget_4;
    QListWidget *listWidget_2;
    QListWidget *listWidget_3;
    QWidget *tab_3;
    QWidget *tab_5;
    QTextEdit *textEdit_2;
    QTextEdit *textEdit_3;
    QTextEdit *textEdit_4;
    QLabel *label_26;
    QPushButton *pushButton_12;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *CharSheet)
    {
        if (CharSheet->objectName().isEmpty())
            CharSheet->setObjectName(QString::fromUtf8("CharSheet"));
        CharSheet->resize(894, 704);
        actionNew_Character = new QAction(CharSheet);
        actionNew_Character->setObjectName(QString::fromUtf8("actionNew_Character"));
        actionLoad_Character = new QAction(CharSheet);
        actionLoad_Character->setObjectName(QString::fromUtf8("actionLoad_Character"));
        actionSave_Character = new QAction(CharSheet);
        actionSave_Character->setObjectName(QString::fromUtf8("actionSave_Character"));
        centralWidget = new QWidget(CharSheet);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 0, 891, 491));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        pic = new QLabel(tab);
        pic->setObjectName(QString::fromUtf8("pic"));
        pic->setGeometry(QRect(450, 140, 421, 301));
        textEdit = new QTextEdit(tab);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(320, 20, 291, 61));
        label_7 = new QLabel(tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(20, 290, 67, 17));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 50, 61, 20));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(20, 200, 67, 17));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 160, 67, 17));
        Wieght = new QLineEdit(tab);
        Wieght->setObjectName(QString::fromUtf8("Wieght"));
        Wieght->setGeometry(QRect(20, 180, 61, 21));
        label_12 = new QLabel(tab);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(240, 90, 67, 17));
        label_8 = new QLabel(tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(20, 330, 67, 17));
        label_11 = new QLabel(tab);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(240, 0, 91, 17));
        comboBox = new QComboBox(tab);
        comboBox->setObjectName(QString::fromUtf8("comboBox"));
        comboBox->setGeometry(QRect(20, 350, 191, 27));
        lineEdit = new QLineEdit(tab);
        lineEdit->setObjectName(QString::fromUtf8("lineEdit"));
        lineEdit->setGeometry(QRect(20, 130, 61, 21));
        Religion = new QLineEdit(tab);
        Religion->setObjectName(QString::fromUtf8("Religion"));
        Religion->setGeometry(QRect(20, 420, 111, 21));
        Size = new QLineEdit(tab);
        Size->setObjectName(QString::fromUtf8("Size"));
        Size->setGeometry(QRect(20, 310, 81, 21));
        CharName = new QLineEdit(tab);
        CharName->setObjectName(QString::fromUtf8("CharName"));
        CharName->setGeometry(QRect(10, 20, 191, 21));
        label = new QLabel(tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(20, 0, 111, 20));
        label_10 = new QLabel(tab);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(530, 100, 67, 17));
        label_6 = new QLabel(tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(20, 240, 67, 17));
        pushButton = new QPushButton(tab);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(610, 90, 31, 27));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(20, 110, 67, 17));
        label_9 = new QLabel(tab);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 400, 67, 17));
        Height = new QLineEdit(tab);
        Height->setObjectName(QString::fromUtf8("Height"));
        Height->setGeometry(QRect(20, 220, 61, 21));
        listWidget = new QListWidget(tab);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(240, 120, 141, 301));
        lineEdit_7 = new QLineEdit(tab);
        lineEdit_7->setObjectName(QString::fromUtf8("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(10, 70, 191, 21));
        lineEdit_8 = new QLineEdit(tab);
        lineEdit_8->setObjectName(QString::fromUtf8("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(20, 260, 121, 21));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tableWidget = new QTableWidget(tab_2);
        if (tableWidget->columnCount() < 2)
            tableWidget->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidget->rowCount() < 6)
            tableWidget->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(3, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(4, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget->setVerticalHeaderItem(5, __qtablewidgetitem7);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(0, 30, 301, 211));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 10, 67, 17));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(590, 0, 67, 17));
        lineEdit_2 = new QLineEdit(tab_2);
        lineEdit_2->setObjectName(QString::fromUtf8("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(592, 20, 71, 21));
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(590, 40, 67, 17));
        lineEdit_3 = new QLineEdit(tab_2);
        lineEdit_3->setObjectName(QString::fromUtf8("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(592, 60, 71, 21));
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(460, 0, 101, 17));
        lineEdit_4 = new QLineEdit(tab_2);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(480, 20, 41, 21));
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(490, 40, 67, 16));
        lineEdit_5 = new QLineEdit(tab_2);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(440, 60, 121, 21));
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 250, 67, 17));
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(140, 250, 41, 17));
        lineEdit_6 = new QLineEdit(tab_2);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(182, 250, 51, 21));
        tableWidget_3 = new QTableWidget(tab_2);
        tableWidget_3->setObjectName(QString::fromUtf8("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(0, 270, 641, 201));
        pushButton_8 = new QPushButton(tab_2);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(612, 162, 37, 22));
        pushButton_9 = new QPushButton(tab_2);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(612, 190, 37, 22));
        pushButton_10 = new QPushButton(tab_2);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(612, 218, 37, 21));
        pushButton_2 = new QPushButton(tab_2);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(301, 61, 39, 24));
        pushButton_3 = new QPushButton(tab_2);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(301, 91, 39, 23));
        pushButton_4 = new QPushButton(tab_2);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(301, 120, 39, 23));
        pushButton_5 = new QPushButton(tab_2);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(301, 149, 39, 23));
        pushButton_6 = new QPushButton(tab_2);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(301, 178, 39, 23));
        pushButton_7 = new QPushButton(tab_2);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(301, 207, 39, 23));
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(431, 111, 100, 17));
        tableWidget_2 = new QTableWidget(tab_2);
        if (tableWidget_2->columnCount() < 1)
            tableWidget_2->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_2->setHorizontalHeaderItem(0, __qtablewidgetitem8);
        if (tableWidget_2->rowCount() < 3)
            tableWidget_2->setRowCount(3);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(0, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(1, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_2->setVerticalHeaderItem(2, __qtablewidgetitem11);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(431, 134, 179, 121));
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_21 = new QLabel(tab_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(0, 0, 67, 17));
        progressBar = new QProgressBar(tab_4);
        progressBar->setObjectName(QString::fromUtf8("progressBar"));
        progressBar->setGeometry(QRect(67, 0, 371, 20));
        progressBar->setValue(24);
        label_22 = new QLabel(tab_4);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(460, 0, 41, 17));
        progressBar_2 = new QProgressBar(tab_4);
        progressBar_2->setObjectName(QString::fromUtf8("progressBar_2"));
        progressBar_2->setGeometry(QRect(510, 0, 361, 21));
        progressBar_2->setValue(24);
        label_23 = new QLabel(tab_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(0, 30, 91, 17));
        label_24 = new QLabel(tab_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(520, 30, 67, 17));
        label_25 = new QLabel(tab_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(720, 30, 67, 17));
        tableWidget_4 = new QTableWidget(tab_4);
        if (tableWidget_4->columnCount() < 2)
            tableWidget_4->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(0, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget_4->setHorizontalHeaderItem(1, __qtablewidgetitem13);
        if (tableWidget_4->rowCount() < 45)
            tableWidget_4->setRowCount(45);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(0, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(1, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(2, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(3, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(4, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(5, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(6, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(7, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(8, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(9, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(10, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(11, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(12, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(13, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(14, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(15, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(16, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(17, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(18, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(19, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(20, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(21, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(22, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(23, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(24, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(25, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(26, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(27, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(28, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(29, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(30, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(31, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(32, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(33, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(34, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(35, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(36, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(37, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(38, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(39, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(40, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(41, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(42, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(43, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableWidget_4->setVerticalHeaderItem(44, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWidget_4->setItem(0, 0, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableWidget_4->setItem(1, 0, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWidget_4->setItem(2, 0, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableWidget_4->setItem(3, 0, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWidget_4->setItem(4, 0, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        tableWidget_4->setItem(5, 0, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWidget_4->setItem(6, 0, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        tableWidget_4->setItem(7, 0, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWidget_4->setItem(8, 0, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        tableWidget_4->setItem(9, 0, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWidget_4->setItem(10, 0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWidget_4->setItem(11, 0, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWidget_4->setItem(12, 0, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWidget_4->setItem(13, 0, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWidget_4->setItem(14, 0, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWidget_4->setItem(15, 0, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget_4->setItem(16, 0, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget_4->setItem(17, 0, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget_4->setItem(18, 0, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget_4->setItem(19, 0, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        tableWidget_4->setItem(20, 0, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget_4->setItem(21, 0, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWidget_4->setItem(22, 0, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWidget_4->setItem(23, 0, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWidget_4->setItem(24, 0, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget_4->setItem(25, 0, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        tableWidget_4->setItem(26, 0, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget_4->setItem(27, 0, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWidget_4->setItem(28, 0, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableWidget_4->setItem(29, 0, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        tableWidget_4->setItem(30, 0, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        tableWidget_4->setItem(31, 0, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        tableWidget_4->setItem(32, 0, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget_4->setItem(33, 0, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget_4->setItem(34, 0, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        tableWidget_4->setItem(35, 0, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget_4->setItem(36, 0, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget_4->setItem(37, 0, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        tableWidget_4->setItem(38, 0, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        tableWidget_4->setItem(39, 0, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        tableWidget_4->setItem(40, 0, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        tableWidget_4->setItem(41, 0, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        tableWidget_4->setItem(42, 0, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        tableWidget_4->setItem(43, 0, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        tableWidget_4->setItem(44, 0, __qtablewidgetitem103);
        tableWidget_4->setObjectName(QString::fromUtf8("tableWidget_4"));
        tableWidget_4->setGeometry(QRect(0, 50, 431, 401));
        listWidget_2 = new QListWidget(tab_4);
        new QListWidgetItem(listWidget_2);
        listWidget_2->setObjectName(QString::fromUtf8("listWidget_2"));
        listWidget_2->setGeometry(QRect(510, 50, 171, 401));
        listWidget_3 = new QListWidget(tab_4);
        listWidget_3->setObjectName(QString::fromUtf8("listWidget_3"));
        listWidget_3->setGeometry(QRect(710, 50, 171, 401));
        tabWidget->addTab(tab_4, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tabWidget->addTab(tab_3, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tabWidget->addTab(tab_5, QString());
        textEdit_2 = new QTextEdit(centralWidget);
        textEdit_2->setObjectName(QString::fromUtf8("textEdit_2"));
        textEdit_2->setGeometry(QRect(10, 490, 391, 151));
        textEdit_3 = new QTextEdit(centralWidget);
        textEdit_3->setObjectName(QString::fromUtf8("textEdit_3"));
        textEdit_3->setGeometry(QRect(773, 490, 111, 151));
        textEdit_4 = new QTextEdit(centralWidget);
        textEdit_4->setObjectName(QString::fromUtf8("textEdit_4"));
        textEdit_4->setGeometry(QRect(650, 610, 101, 31));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(650, 580, 67, 17));
        pushButton_12 = new QPushButton(centralWidget);
        pushButton_12->setObjectName(QString::fromUtf8("pushButton_12"));
        pushButton_12->setGeometry(QRect(650, 500, 99, 27));
        CharSheet->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(CharSheet);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 894, 25));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        CharSheet->setMenuBar(menuBar);
        mainToolBar = new QToolBar(CharSheet);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        CharSheet->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(CharSheet);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        CharSheet->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuFile->addAction(actionNew_Character);
        menuFile->addAction(actionLoad_Character);
        menuFile->addAction(actionSave_Character);

        retranslateUi(CharSheet);

        tabWidget->setCurrentIndex(0);
        comboBox->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(CharSheet);
    } // setupUi

    void retranslateUi(QMainWindow *CharSheet)
    {
        CharSheet->setWindowTitle(QApplication::translate("CharSheet", "CharSheet", 0, QApplication::UnicodeUTF8));
        actionNew_Character->setText(QApplication::translate("CharSheet", "New Character", 0, QApplication::UnicodeUTF8));
        actionLoad_Character->setText(QApplication::translate("CharSheet", "Load Character", 0, QApplication::UnicodeUTF8));
        actionSave_Character->setText(QApplication::translate("CharSheet", "Save Character", 0, QApplication::UnicodeUTF8));
        pic->setText(QString());
        label_7->setText(QApplication::translate("CharSheet", "Rozmiar", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("CharSheet", "Rasa", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("CharSheet", "Wzrost", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("CharSheet", "Waga", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("CharSheet", "J\304\231zyki", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("CharSheet", "Charakter", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("CharSheet", "Opis postaci", 0, QApplication::UnicodeUTF8));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("CharSheet", "praworz\304\205dny dobry", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "neutralny dobry", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "chaotyczny dobry", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "praworz\304\205dny neutralny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "prawdziwie neutralny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "chaotyczny neutralny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "praworz\304\205dny z\305\202y", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "neutralny z\305\202y", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("CharSheet", "chaotyczny z\305\202y", 0, QApplication::UnicodeUTF8)
        );
        CharName->setText(QString());
        label->setText(QApplication::translate("CharSheet", "Nazwa Postaci", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("CharSheet", "Wygl\304\205d", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("CharSheet", "P\305\202e\304\207", 0, QApplication::UnicodeUTF8));
        pushButton->setText(QApplication::translate("CharSheet", "...", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("CharSheet", "Wiek", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("CharSheet", "Wiara", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("CharSheet", "G\305\202\303\263wne Dane", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("CharSheet", "Warto\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("CharSheet", "Modyfikator", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget->verticalHeaderItem(0);
        ___qtablewidgetitem2->setText(QApplication::translate("CharSheet", "Si\305\202a", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget->verticalHeaderItem(1);
        ___qtablewidgetitem3->setText(QApplication::translate("CharSheet", "Zr\304\231czno\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget->verticalHeaderItem(2);
        ___qtablewidgetitem4->setText(QApplication::translate("CharSheet", "Budowa", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget->verticalHeaderItem(3);
        ___qtablewidgetitem5->setText(QApplication::translate("CharSheet", "Intelekt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget->verticalHeaderItem(4);
        ___qtablewidgetitem6->setText(QApplication::translate("CharSheet", "Roztropno\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget->verticalHeaderItem(5);
        ___qtablewidgetitem7->setText(QApplication::translate("CharSheet", "Charyzma", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("CharSheet", "Atrybuty", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("CharSheet", "Szybko\305\233\304\207", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("CharSheet", "Inicjatywa", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("CharSheet", "Poziom postaci", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("CharSheet", "PD", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("CharSheet", "Ataki", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("CharSheet", "Unik:", 0, QApplication::UnicodeUTF8));
        pushButton_8->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_9->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_10->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_2->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_3->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_4->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        pushButton_7->setText(QApplication::translate("CharSheet", "Rzu\304\207", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("CharSheet", "Rzuty obronne", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_2->horizontalHeaderItem(0);
        ___qtablewidgetitem8->setText(QApplication::translate("CharSheet", "Warto\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_2->verticalHeaderItem(0);
        ___qtablewidgetitem9->setText(QApplication::translate("CharSheet", "Wytrwa\305\202o\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_2->verticalHeaderItem(1);
        ___qtablewidgetitem10->setText(QApplication::translate("CharSheet", "Refleks", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_2->verticalHeaderItem(2);
        ___qtablewidgetitem11->setText(QApplication::translate("CharSheet", "Wola", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("CharSheet", "Statystyki", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("CharSheet", "Stamina", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("CharSheet", "Mana", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("CharSheet", "Umiej\304\231tno\305\233ci", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("CharSheet", "Atuty", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("CharSheet", "Strategie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_4->horizontalHeaderItem(0);
        ___qtablewidgetitem12->setText(QApplication::translate("CharSheet", "atr.", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_4->horizontalHeaderItem(1);
        ___qtablewidgetitem13->setText(QApplication::translate("CharSheet", "Watro\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_4->verticalHeaderItem(0);
        ___qtablewidgetitem14->setText(QApplication::translate("CharSheet", "Alchemia", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_4->verticalHeaderItem(1);
        ___qtablewidgetitem15->setText(QApplication::translate("CharSheet", "Blefowanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_4->verticalHeaderItem(2);
        ___qtablewidgetitem16->setText(QApplication::translate("CharSheet", "Cichy ch\303\263d", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_4->verticalHeaderItem(3);
        ___qtablewidgetitem17->setText(QApplication::translate("CharSheet", "Czarostwo", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_4->verticalHeaderItem(4);
        ___qtablewidgetitem18->setText(QApplication::translate("CharSheet", "Czytanie z warg", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_4->verticalHeaderItem(5);
        ___qtablewidgetitem19->setText(QApplication::translate("CharSheet", "Dyplomacja", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_4->verticalHeaderItem(6);
        ___qtablewidgetitem20->setText(QApplication::translate("CharSheet", "Fa\305\202szerstwo", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_4->verticalHeaderItem(7);
        ___qtablewidgetitem21->setText(QApplication::translate("CharSheet", "Je\305\272dziectwo", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget_4->verticalHeaderItem(8);
        ___qtablewidgetitem22->setText(QApplication::translate("CharSheet", "Koncentracja", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget_4->verticalHeaderItem(9);
        ___qtablewidgetitem23->setText(QApplication::translate("CharSheet", "Kradzie\305\274", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget_4->verticalHeaderItem(10);
        ___qtablewidgetitem24->setText(QApplication::translate("CharSheet", "Leczenie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget_4->verticalHeaderItem(11);
        ___qtablewidgetitem25->setText(QApplication::translate("CharSheet", "Nas\305\202uchiwanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget_4->verticalHeaderItem(12);
        ___qtablewidgetitem26->setText(QApplication::translate("CharSheet", "Odcyfrowywanie zapis\303\263w", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget_4->verticalHeaderItem(13);
        ___qtablewidgetitem27->setText(QApplication::translate("CharSheet", "Otwieranie zamk\303\263w", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget_4->verticalHeaderItem(14);
        ___qtablewidgetitem28->setText(QApplication::translate("CharSheet", "P\305\202ywanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_4->verticalHeaderItem(15);
        ___qtablewidgetitem29->setText(QApplication::translate("CharSheet", "Post. ze zwierz\304\231tami", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_4->verticalHeaderItem(16);
        ___qtablewidgetitem30->setText(QApplication::translate("CharSheet", "P\303\263\305\202s\305\202\303\263wka", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_4->verticalHeaderItem(17);
        ___qtablewidgetitem31->setText(QApplication::translate("CharSheet", "Profesja", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_4->verticalHeaderItem(18);
        ___qtablewidgetitem32->setText(QApplication::translate("CharSheet", "Przebieranie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_4->verticalHeaderItem(19);
        ___qtablewidgetitem33->setText(QApplication::translate("CharSheet", "Przeszukiwanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_4->verticalHeaderItem(20);
        ___qtablewidgetitem34->setText(QApplication::translate("CharSheet", "R\303\263wnowaga", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_4->verticalHeaderItem(21);
        ___qtablewidgetitem35->setText(QApplication::translate("CharSheet", "Rzemios\305\202o", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_4->verticalHeaderItem(22);
        ___qtablewidgetitem36->setText(QApplication::translate("CharSheet", "Skakanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_4->verticalHeaderItem(23);
        ___qtablewidgetitem37->setText(QApplication::translate("CharSheet", "Stosowanie liny", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_4->verticalHeaderItem(24);
        ___qtablewidgetitem38->setText(QApplication::translate("CharSheet", "Stosowanie mag. rzeczy", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_4->verticalHeaderItem(25);
        ___qtablewidgetitem39->setText(QApplication::translate("CharSheet", "Szacowanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_4->verticalHeaderItem(26);
        ___qtablewidgetitem40->setText(QApplication::translate("CharSheet", "Tajniki dziczy", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_4->verticalHeaderItem(27);
        ___qtablewidgetitem41->setText(QApplication::translate("CharSheet", "Ukrywanie si\304\231", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_4->verticalHeaderItem(28);
        ___qtablewidgetitem42->setText(QApplication::translate("CharSheet", "Unieszkodliwianie urz\304\205dze\305\204", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_4->verticalHeaderItem(29);
        ___qtablewidgetitem43->setText(QApplication::translate("CharSheet", "Upadanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_4->verticalHeaderItem(30);
        ___qtablewidgetitem44->setText(QApplication::translate("CharSheet", "Wiedza (tajemna)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_4->verticalHeaderItem(31);
        ___qtablewidgetitem45->setText(QApplication::translate("CharSheet", "Wiedza (natura)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_4->verticalHeaderItem(32);
        ___qtablewidgetitem46->setText(QApplication::translate("CharSheet", "Wiedza (miejscowa)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_4->verticalHeaderItem(33);
        ___qtablewidgetitem47->setText(QApplication::translate("CharSheet", "Wiedza (religia)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_4->verticalHeaderItem(34);
        ___qtablewidgetitem48->setText(QApplication::translate("CharSheet", "Wiedza (historia)", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget_4->verticalHeaderItem(35);
        ___qtablewidgetitem49->setText(QApplication::translate("CharSheet", "Wr\303\263\305\274enie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget_4->verticalHeaderItem(36);
        ___qtablewidgetitem50->setText(QApplication::translate("CharSheet", "Wspinaczka", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget_4->verticalHeaderItem(37);
        ___qtablewidgetitem51->setText(QApplication::translate("CharSheet", "Wyczucie kierunku", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget_4->verticalHeaderItem(38);
        ___qtablewidgetitem52->setText(QApplication::translate("CharSheet", "Wyczucie pobudek", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget_4->verticalHeaderItem(39);
        ___qtablewidgetitem53->setText(QApplication::translate("CharSheet", "Wyst\304\231py", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget_4->verticalHeaderItem(40);
        ___qtablewidgetitem54->setText(QApplication::translate("CharSheet", "Wyzwalanie si\304\231", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget_4->verticalHeaderItem(41);
        ___qtablewidgetitem55->setText(QApplication::translate("CharSheet", "Zastraszanie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget_4->verticalHeaderItem(42);
        ___qtablewidgetitem56->setText(QApplication::translate("CharSheet", "Zauwa\305\274anie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget_4->verticalHeaderItem(43);
        ___qtablewidgetitem57->setText(QApplication::translate("CharSheet", "Zbieranie informacji", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget_4->verticalHeaderItem(44);
        ___qtablewidgetitem58->setText(QApplication::translate("CharSheet", "Zwierz\304\231ca empatia", 0, QApplication::UnicodeUTF8));

        const bool __sortingEnabled = tableWidget_4->isSortingEnabled();
        tableWidget_4->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget_4->item(0, 0);
        ___qtablewidgetitem59->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget_4->item(1, 0);
        ___qtablewidgetitem60->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget_4->item(2, 0);
        ___qtablewidgetitem61->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget_4->item(3, 0);
        ___qtablewidgetitem62->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget_4->item(4, 0);
        ___qtablewidgetitem63->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget_4->item(5, 0);
        ___qtablewidgetitem64->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget_4->item(6, 0);
        ___qtablewidgetitem65->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget_4->item(7, 0);
        ___qtablewidgetitem66->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget_4->item(8, 0);
        ___qtablewidgetitem67->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget_4->item(9, 0);
        ___qtablewidgetitem68->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget_4->item(10, 0);
        ___qtablewidgetitem69->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget_4->item(11, 0);
        ___qtablewidgetitem70->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget_4->item(12, 0);
        ___qtablewidgetitem71->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget_4->item(13, 0);
        ___qtablewidgetitem72->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget_4->item(14, 0);
        ___qtablewidgetitem73->setText(QApplication::translate("CharSheet", "s", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget_4->item(15, 0);
        ___qtablewidgetitem74->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget_4->item(16, 0);
        ___qtablewidgetitem75->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget_4->item(17, 0);
        ___qtablewidgetitem76->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget_4->item(18, 0);
        ___qtablewidgetitem77->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget_4->item(19, 0);
        ___qtablewidgetitem78->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget_4->item(20, 0);
        ___qtablewidgetitem79->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget_4->item(21, 0);
        ___qtablewidgetitem80->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem81 = tableWidget_4->item(22, 0);
        ___qtablewidgetitem81->setText(QApplication::translate("CharSheet", "s", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem82 = tableWidget_4->item(23, 0);
        ___qtablewidgetitem82->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem83 = tableWidget_4->item(24, 0);
        ___qtablewidgetitem83->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem84 = tableWidget_4->item(25, 0);
        ___qtablewidgetitem84->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem85 = tableWidget_4->item(26, 0);
        ___qtablewidgetitem85->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem86 = tableWidget_4->item(27, 0);
        ___qtablewidgetitem86->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem87 = tableWidget_4->item(28, 0);
        ___qtablewidgetitem87->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem88 = tableWidget_4->item(29, 0);
        ___qtablewidgetitem88->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem89 = tableWidget_4->item(30, 0);
        ___qtablewidgetitem89->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem90 = tableWidget_4->item(31, 0);
        ___qtablewidgetitem90->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem91 = tableWidget_4->item(32, 0);
        ___qtablewidgetitem91->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem92 = tableWidget_4->item(33, 0);
        ___qtablewidgetitem92->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem93 = tableWidget_4->item(34, 0);
        ___qtablewidgetitem93->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem94 = tableWidget_4->item(35, 0);
        ___qtablewidgetitem94->setText(QApplication::translate("CharSheet", "int", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem95 = tableWidget_4->item(36, 0);
        ___qtablewidgetitem95->setText(QApplication::translate("CharSheet", "s", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem96 = tableWidget_4->item(37, 0);
        ___qtablewidgetitem96->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem97 = tableWidget_4->item(38, 0);
        ___qtablewidgetitem97->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem98 = tableWidget_4->item(39, 0);
        ___qtablewidgetitem98->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem99 = tableWidget_4->item(40, 0);
        ___qtablewidgetitem99->setText(QApplication::translate("CharSheet", "zr", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem100 = tableWidget_4->item(41, 0);
        ___qtablewidgetitem100->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem101 = tableWidget_4->item(42, 0);
        ___qtablewidgetitem101->setText(QApplication::translate("CharSheet", "rzt", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem102 = tableWidget_4->item(43, 0);
        ___qtablewidgetitem102->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem103 = tableWidget_4->item(44, 0);
        ___qtablewidgetitem103->setText(QApplication::translate("CharSheet", "cha", 0, QApplication::UnicodeUTF8));
        tableWidget_4->setSortingEnabled(__sortingEnabled);


        const bool __sortingEnabled1 = listWidget_2->isSortingEnabled();
        listWidget_2->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget_2->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("CharSheet", "Specjalna cecha", 0, QApplication::UnicodeUTF8));
        listWidget_2->setSortingEnabled(__sortingEnabled1);

        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("CharSheet", "Zdolno\305\233ci", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("CharSheet", "Ekwipunek", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("CharSheet", "Towarzysze", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("CharSheet", "Rzuty", 0, QApplication::UnicodeUTF8));
        pushButton_12->setText(QApplication::translate("CharSheet", "Poziom!", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("CharSheet", "File", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class CharSheet: public Ui_CharSheet {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CHARSHEET_H
